version: '3.7'
services:
  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: on-failure
    environment:
      - SA_PASSWORD=mssql@Admin
      - ACCEPT_EULA="Y"
    user: root
    volumes:
      - mssql_data:/var/opt/mssql/data
    ports:
      - 1433:1433

  postgres:
    container_name: postgres
    image: postgres:14
    restart: on-failure
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: pg
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongodb:
    image: mongo:5.0-focal
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: myapi-db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
volumes:
  mongodb_data:
  mssql_data:
  pgdata: